name: scribble
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.2
  image_gallery_saver: ^1.6.9
  socket_io_client: 2.0.0-beta.4-nullsafety.0
  flutter_redux: ^0.9.0
  go_router: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
